version: 2
updates:
- package-ecosystem: maven
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: "06:00"
    timezone: Europe/Zurich
  open-pull-requests-limit: 10
  reviewers:
  - patbaumgartner
  assignees:
  - patbaumgartner
  commit-message:
    prefix: deps(java)
    include: scope
  labels:
  - dependencies
  - java
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
    day: monday
    time: "06:00"
    timezone: Europe/Zurich
  open-pull-requests-limit: 5
  reviewers:
  - patbaumgartner
  assignees:
  - patbaumgartner
  commit-message:
    prefix: ci
    include: scope
  labels:
  - dependencies
  - github-actions
