FROM paketobuildpacks/run:base-cnb

USER root

## Idea from: https://blog.adoptopenjdk.net/2021/01/prerequisites-for-font-support-in-adoptopenjdk/
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    libfreetype6 \
    fontconfig \
    fonts-dejavu \
  && rm -rf /var/lib/apt/lists/*

USER cnb
