# This workflow will build a Docker Container using Maven and then publish it to Dockerhub when change was made.

name: Maven Build and Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build custom run image
        uses: docker/build-push-action@v7.3.0
        with:
          context: .
          file: Dockerfile.base-cnb
          load: true
          tags: patbaumgartner/lovebox-telegram-sender-run:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Push custom run image (latest)
        if: github.event_name != 'pull_request'
        run: docker push patbaumgartner/lovebox-telegram-sender-run:latest

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean verify --batch-mode --no-transfer-progress

      - name: Build native image with Maven
        # -Pnative compiles a GraalVM native image via the Paketo native buildpack.
        run: mvn -Pnative spring-boot:build-image --batch-mode --no-transfer-progress -DskipTests

      - name: Tag & push image (latest)
        if: github.event_name != 'pull_request'
        run: |
          VERSION="$(mvn -q --no-transfer-progress help:evaluate -Dexpression=project.version -DforceStdout)"
          docker tag \
            patbaumgartner/lovebox-telegram-sender:"$VERSION" \
            patbaumgartner/lovebox-telegram-sender:latest
          docker push patbaumgartner/lovebox-telegram-sender:latest
